-
  hosts: all
  remote_user: isadmin
  become_method: sudo
  become_user: root
  gather_facts: false
  tasks:
  - name: Install python
    raw: bash -c "test -e /usr/bin/python || (yum -y install python || (apt-get -qqy update && apt-get -qqy install python))"
  - name: Gathering facts
    setup:

  - name: Create directory to save logs of secondary logging
    file:
      path: "{{ item.path }}"
      state: directory
    with_items:
      - { path: '/var/log/sudo_historylogs' }
      - { path: '/var/log/users_historylogs' }

  - name: Make entries in bashrc file.
    lineinfile:
      path: /root/.bashrc
      line: "{{ item.expt }}"
      state: present
    with_items:
      - { expt: "export HISTSIZE=10000" }
      - { expt: "export HISTTIMEFORMAT='%F %T' " }
      - { expt: "export HISTFILE=/var/log/sudo_historylogs/history-sudo-$(who am i | awk '{print $1}';exit)-$(date +%F) " }
      - { expt: "export PROMPT_COMMAND='history -a' " }
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: source bashrc
    shell: 'source /root/.bashrc'
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: And set the sticky bit on user historylog
    shell: 'chmod +t  /var/log/users_historylogs/'

  - name: Delete history_log.sh file is exist
    file:
      path: /etc/profile.d/history_log.sh
      state: absent
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: Change the permission of history_log.sh
    file:
     path: /etc/profile.d/history_log.sh
     state: touch
     mode: 770
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: Create a new script inside /etc/profile.d/
    blockinfile:
      path: /etc/profile.d/history_log.sh
      block: |
       _who_am_i=$(who am i|awk '{print $1}')
       _ID=$(id -u $_who_am_i)
       if [ "$_ID" > 0 ]
       then
       export HISTSIZE=10000
       export HISTTIMEFORMAT='%F %T '
       export HISTFILE=/var/log/users_historylogs/history-users-$(who am i | awk '{print $1}';exit)-$(date +%F)
       export PROMPT_COMMAND='history -a'
       fi
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: source bashrc
    shell: 'source /etc/profile.d/history_log.sh'
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: Adding /etc/bash.bashrc for ubuntu
    blockinfile:
      path: /etc/bash.bashrc
      block: |
       _who_am_i=$(who am i|awk '{print $1}')
       _ID=$(id -u $_who_am_i)
       if [ "$_ID" -gt 0 ]
       then
       export HISTSIZE=10000
       export HISTTIMEFORMAT='%F %T '
       export HISTFILE=/var/log/users_historylogs/history-users-$(who am i | awk '{print $1}';exit)-$(date +%F)
       export PROMPT_COMMAND='history -a;date >> $HISTFILE'
       fi
       if [ "$_ID" == 0 ]
       then
       export HISTSIZE=10000
       export HISTTIMEFORMAT='%F %T '
       export HISTFILE=/var/log/sudo_historylogs/history-sudo-$(who am i | awk '{print $1}';exit)-$(date +%F)
       export PROMPT_COMMAND='history -a'
       fi
      state: present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: source bashrc
    shell: source /etc/bash.bashrc
    args:
      executable: /bin/bash
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      
   
