- hosts: all
  tasks:
  - name: Ansible check file exists example.
    stat:
      path: /opt/IBM/Cobalt
    register: file_details

  - debug:
      msg: "The file or directory exists"
    when: file_details.stat.exists
