-
  hosts: all
  remote_user: isadmin
  sudo: yes
  tasks:
    - name: Sending an e-mail using Gmail SMTP servers
      mail:
       host: smtp.gmail.com
       port: 587
       username: rajibuldevops@gmail.com
       password: rajibul123
       to: John Smith <skrajibulhuda@gmail.com>
       subject: Ansible-report
       body: System {{ ansible_hostname }} has been successfully provisioned.
      delegate_to: localhost
