#Installation and configuration for adding new server 
- hosts: all
  remote_user: isadmin
  sudo: yes
  tasks:
  - name: Download nrpe and Unarchive a file 
    unarchive:
     src: https://assets.nagios.com/downloads/nagiosxi/agents/linux-nrpe-agent.tar.gz
     dest: /tmp
     remote_src: yes
  - name: save iptables, Uncomment below line (4 to 7) in A-subcomponents file and uncomment line in fullinstall
    shell: | 
       iptables-save > /opt/iptables.backup
       sed -i '4,7 s/^/#/' A-subcomponents
       sed -i '183 s/^/#/' fullinstall
    args:
     chdir: /tmp/linux-nrpe-agent
  - name: install
    command: ./fullinstall -n
    args:
     chdir: /tmp/linux-nrpe-agent
#    async: 20
#    poll: 10
  - name: allow host 
    replace:
     path: /etc/xinetd.d/nrpe
     regexp: 'only_from       = 127.0.0.1'
     replace: 'only_from  =  9.45.203.33 9.45.203.34 9.45.203.42 9.45.203.43 127.0.0.1'
  - name:  Restart xinetd service
    service:
     name: xinetd
     state: restarted
  - name: Add rule 5666 
    command: iptables -A INPUT -p tcp -m tcp --dport 5666 -m state --state NEW,ESTABLISHED -j ACCEPT
  - name: Add rule 5667
    command: iptables -A INPUT -p tcp -m tcp --dport 5667 -m state --state NEW,ESTABLISHED -j ACCEPT
