--- #using file module
- hosts: all
  remote_user: isadmin
  sudo: yes
  gather_facts: no
  connection: ssh
  tasks:
  - name: Unarchive a file 
    unarchive:
     src: https://assets.nagios.com/downloads/nagiosxi/agents/linux-nrpe-agent.tar.gz
     dest: /tmp
     remote_src: yes
