- hosts: all
  remote_user: isadmin
  sudo: yes
  tasks:
   - name: To make the accesshubid password never expire
     shell: chage -m 0 -M 99999 -I -1 -E -1 accesshubid
     ignore_errors: yes 
     
