-
  hosts: all
  remote_user: isadmin
  become: yes
  become_method: sudo
###
  pre_tasks:
  - name: Install python
    raw: bash -c "test -e /usr/bin/python || (yum -y install python || (apt-get -qqy update && apt-get -qqy install python))"
###
  - name: Gathering facts
    setup:
###
  tasks:
###
  - name: Adding Base Repository for CentOS 6
    shell: |
          wget https://bzrepo01.innovate.ibm.com/yum/centos/yum/bzrepo01/CentOS6-Base.repo -O /etc/yum.repos.d/CentOS-Base.repo
          chown root:root /etc/yum.repos.d/CentOS-Base.repo
          chmod 644 /etc/yum.repos.d/CentOS-Base.repo
    args:
      executable: /bin/bash
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
###
  - name: Adding Base Repository for CentOS 7
    shell: |
          wget https://bzrepo01.innovate.ibm.com/yum/centos/yum/bzrepo01/CentOS7-Base.repo -O /etc/yum.repos.d/CentOS-Base.repo
          chown root:root /etc/yum.repos.d/CentOS-Base.repo
          chmod 644 /etc/yum.repos.d/CentOS-Base.repo
    args:
      executable: /bin/bash
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
###
  - name: Adding Base Repository for RedHat 6
    shell: |
          wget https://bzrepo01.innovate.ibm.com/yum/redhat/yum/bzrepo01/rhel6-Base.repo -O /etc/yum.repos.d/rhel6-Base.repo
          chown root:root /etc/yum.repos.d/rhel6-Base.repo
          chmod 644 /etc/yum.repos.d/rhel6-Base.repo
    args:
      executable: /bin/bash
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6'
###
  - name: Adding Base Repository for RedHat 7
    shell: |
          wget https://bzrepo01.innovate.ibm.com/yum/redhat/yum/bzrepo01/rhel6-Base.repo -O /etc/yum.repos.d/rhel7-Base.repo
          chown root:root /etc/yum.repos.d/rhel7-Base.repo
          chmod 644 /etc/yum.repos.d/rhel7-Base.repo
    args:
      executable: /bin/bash
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
###
  - name: Adding NetEng Tools Repository for CentOS 6 and 7
    shell: |
          wget https://bzrepo01.innovate.ibm.com/yum/netengtools/yum/bzrepo01/netengtools_centos.repo -O /etc/yum.repos.d/netengtools.repo
          chown root:root /etc/yum.repos.d/netengtools.repo
          chmod 644 /etc/yum.repos.d/netengtools.repo
    args:
      executable: /bin/bash
    when: ansible_distribution == 'CentOS' and ( ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7' )
###
  - name: Adding NetEng Tools Repository for RedHat 6 and 7
    shell: |
          wget https://bzrepo01.innovate.ibm.com/yum/netengtools/yum/bzrepo01/netengtools_redhat.repo -O /etc/yum.repos.d/netengtools.repo
          chown root:root /etc/yum.repos.d/netengtools.repo
          chmod 644 /etc/yum.repos.d/netengtools.repo
    args:
      executable: /bin/bash
    when: ansible_distribution == 'RedHat' and ( ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7' )
###
  - name: Cleaning up prior patch & tonic tools from CentOS and RedHat
    yum:
      name: [ tonic-1.19-RedHat7Server.noarch, lssecfixes-1.10.15-RedHat7Server.noarch ]
      state: absent
    when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' ) and ( ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7' )
###
  - name: Installing NetEng Tools on CentOS and RedHat (v6 or v7)
    yum:
      name: "@netengtools"
      state: latest
      update_cache: yes
    when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' ) and ( ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7' )
###
  - name: Running Identity Collector first time
    shell: /usr/sbin/collector_identity.py -i -s -x -v
    args:
      executable: /bin/bash
    when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' ) and ( ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7' )
###
  - name: Running HealthCheck Collector first time
    shell: /usr/sbin/collector_tonic.py -t -s -x -v
    args:
      executable: /bin/bash
    when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' ) and ( ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7' )
###
  - name: Running Patch Status Collector first time
    shell: /usr/local/lssecfixes/sbin/collector_secfix.py -l -p -s -x -v
    args:
      executable: /bin/bash
    when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' ) and ( ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7' )
###
