- hosts: all
  remote_user: isadmin
  sudo: yes
  tasks:
  
   - name: Configure BZREPO01 CentOS YUM repository CentOS7
     shell: |  
      /usr/bin/curl --silent --output /etc/yum.repos.d/CentOS-Base.repo  https://bzrepo01.innovate.ibm.com/yum/centos/yum/bzrepo01/CentOS7-Base.repo
      chown root:root /etc/yum.repos.d/CentOS-Base.repo
      chmod 0644 /etc/yum.repos.d/CentOS-Base.repo
      /usr/bin/yum clean all
      /usr/bin/yum repolist

   - name: Configure Network Engineering Tools Repository
     shell: |  
      /usr/bin/curl --silent --output /etc/yum.repos.d/netengtools.repo  https://bzrepo01.innovate.ibm.com/yum/netengtools/yum/bzrepo01/netengtools_centos.repo
      chown root:root /etc/yum.repos.d/netengtools.repo
      chmod 0644 /etc/yum.repos.d/netengtools.repo
      /usr/bin/yum clean all
      /usr/bin/yum repolist

   - name: clean up 
     shell: /usr/bin/yum erase tonic-1.19-RedHat7Server.noarch lssecfixes-1.10.15-RedHat7Server.noarch -y 
   
   - name: Configure NetEng Tools
     shell: /usr/bin/yum groupinstall netengtools -y 
    
   - name: Run Tools First Time
     shell: |
       /usr/sbin/collector_identity.py -i -s -x -v
       /usr/sbin/collector_tonic.py -t -s -x -v
       /usr/local/lssecfixes/sbin/collector_secfix.py -l -p -s -x -v

      
